### PR TITLE
set FLUKA4 values to DPMJ and MSTJ

### PR DESCRIPTION
**Pull request by luillo76**
For discussion

### CODE REVIEW

**Comment by afedynitch** [comment]
I think it will be best to run my data comparison suite on the "hybrid" parameters. But I need to reactivate it on my current dev machine and run all the tests. It will take one/half day or so. I will try pushing it into second half of this week.

Do you have any sense for the impact of this difference on "technical" distributions, such as energy deposition or radiation levels?

Edit: I can always put a flag, but there is no good reason for having divergent versions.

**Comment by luillo76** [comment]
Thank for checking. I agree that it's better not to have different sets of parameters.
In that respect, it will be interesting to see the differences from your test suite against data.

In any case, I expect that there will be differences in the energy deposition, as suggested by the enclosed [energy spectra](https://github.com/afedynitch/DPMJET/files/6257718/pp_7TeV_spectra_at_TAS.pdf) in the very forward regions (inside a circle of 3 cm radius at 20 m from IP).

For future reference, I attach here also the files shared previously by email.

[pt distributions](https://github.com/afedynitch/DPMJET/files/6257727/pp_7TeV_pt.pdf)
[pseudo-rapidity distributions](https://github.com/afedynitch/DPMJET/files/6257730/pp_7TeV_rapidity.pdf)
[PARJ values in FLUKA](https://github.com/afedynitch/DPMJET/files/6257737/FLUKA4_p7TeVon_p001_fort.19.txt)
[PARJ values DPMJETIII 19.1.2](https://github.com/afedynitch/DPMJET/files/6257750/DPMJETIII_19.1.2_p7TeVon_p001_fort.19.txt)

Cheers!

**Comment by afedynitch** [comment]
OK. I’ll test it.
Btw.: from the spectra it is not evident that there will be any visible difference in energy deposition. The parameters just move a little bit the phase-space distributions, but total energy and multiplicity per particle species should be very similar if not conserved.

**Comment by afedynitch** [comment]
Attached are some of the comparisons between the generators. The fragmentation parameters from FLUKA are labeled DPMJETIII-19.1F. The differences are not that big, though. Maybe the "F" params look a bit better. I don't mind switching to these parameters by default, and bump the version to 19.2 because of the physics change.

[MCVD.pdf](https://github.com/afedynitch/DPMJET/files/6383118/MCVD.pdf)

Let me know what you think.

**Comment by luillo76** [comment]
Hi @afedynitch , 
thanks a lot for the check.
It's an impressive test suite!
If it is ok for you to switch to the "F" parameters, this is also our preferred options.

Thanks! 
Cheers

**Comment by afedynitch** [comment]
Perfect. Will tag a new version asap.

**Comment by luillo76** [comment]
Hi @afedynitch ,

I realized that I marked this PR as a work in progress since I had thought you're in a better position to make the needed changes.
Should I remove the draft flag? I guess you have all super-powers though!

Cheers, Luigi

**Comment by afedynitch** [comment]
Hi Luigi,

sorry for the delays. I did more testing and recovered one of the reasons for the different parameters. While the impact on LHC and central distributions between the versions is minor, there is some small impact on forward distributions. The muon charge ratio in inclusive fluxes becomes slightly worse with the "new-old" params. Not that it was overwhelmingly great in any of the cases, but still, slightly better. For FLUKA there is no impact since the distributions are PEANUT territory. For nucleus-nucleus things may be different since there are plenty other processes at work (string fusion, more neutron projectiles, etc.). 

I'm inclined to accept this small degradation since it is within "uncertainties" of the model and not qualitatively different. Improving the charge ratio needs more deep work. I'll tie up the testing and will merge at the end of this week.

**Comment by luillo76** [comment]
Hi Anatoli,

thanks for the update.

What do you mean by this sentence?

> For FLUKA there is no impact since the distributions are PEANUT territory.

Collisions at the interaction point should be DPMJET territory.

Cheers Luigi

**Comment by afedynitch** [comment]
The sentence refers to PEANUT being used below 10 TeV lab for pp and pA collisions by default. This is where forward data is available and also where the energy range for the atmospheric muon charge ratio is located. Of course DPMJET is handling collisions at LHC energies, but most of the precise data is at central rapidities, where the 19.2 performs reasonably well and with only minor differences to 19.1.

**Comment by afedynitch** [comment]
Sorry for the delay again. I cleaned up further the code and merged the PR into master. I tagged the new version as 19.2.0.

There was one minor thing that I had to fix for f2py correctly processing the includes ([see this commit](https://github.com/afedynitch/DPMJET/commit/006a88dc43741d46f75e14c9df0bfc11265d1812)). It is just cosmetic and needed for f2py to work, but maybe could not harm to update the common block in FLUKA, too.

**Comment by luillo76** [comment]
Thanks a lot, Anatoli!
I'm doing the last tests on our side and then I will clean everything up.

**Comment by luillo76** [comment]
Everything's clean on my side.
Thanks a lot!

**Pull request merged**
