### PR TITLE
Update to 19.3.1

### PR DESCRIPTION
**Pull request by afedynitch**

### CODE REVIEW

**Comment by luillo76** [comment]
Hello @afedynitch ,

I hope you're doing well.

Does this MR fix the issue related to K+ distribution?

Thanks.
Cheers Luigi

**Comment by afedynitch** [comment]
Hi Luigi,

Yes it does. Long in the tooth but yeah. [See here. ](https://github.com/DPMJET/DPMJET/blob/4fc7e4a1d4b481570fdbfeb7edd34051e4ef9d1f/docs/validation.md)
I'm tagging this now and making a release.

There are also a couple other changes, such as removal of non functional FLUKA common blocks, which were just copied over from an older FLUKA release, used rarely if at all. This required a few changes to the arguments in DPMINI. Let me know if you have any questions regarding these.

Bests,
Anatoli

**Comment by luillo76** [comment]
Thanks Anatoli!

Actually I have an error related to non functional FLUKA common blocks.

I see that they have been removed but there are still references to them inside include/flinclude/inc/flk*
and indeed I have this compilation error:

```
gfortran -c -cpp -DFOR_FLUKA -O3 -Wno-uninitialized -fPIC -std=legacy -I./include/pythia -I./include/phojet -I./include/dpmjet -I./include/flinclude  -o src/dpmjet/DT_EVA2HE.o src/dpmjet/DT_EVA2HE.f   
inc/flkeva:1: Error: Can't open included file '(DIMPAR)'
make: *** [src/dpmjet/DT_EVA2HE.o] Error 1
```

any suggestions?

**Comment by luillo76** [comment]
A workaround might be to copy the relevant FLUKA include files in `DPMJET/include/flinclude`

Probably it is was you had in mind.
Please let me know.

**Comment by afedynitch** [comment]
I think the purpose is that these common block includes should be provided by FLUKA. So there should be another "-I" directive provided to the makefile via some environment variable. In the past, if you would change the includes in FLUKA, you may run into inconsistencies with the old copies in the DPMJET distro.

By default, without the FOR_FLUKA preprocessor directive, DPMJET does not depend on FLUKA common blocks. 

Let me know how I should modify the makefile to fit your workflow, or please make a PR.

**Pull request merged**
